sudo: false
language: node_js
node_js:
- iojs
cache:
  directories:
  - node_modules
script: npm run deploy
deploy:
  provider: heroku
  api_key:
    secure: SClgffk75qB7A5CvqZyckfW8euhb7LQR4HLY6TY/9gnMoZ5lfNx2c6+/DcJ6KKyklheGkxyhTnbSfrirDT5kZR7+m6GwgXrNMNxC8kGZF5r/oVbe5Lf8aX5Lt8Fv2i6iY8mRkldp2SFjM7XTPj0gsjUBGgZYJGXc/cHYwsYT66nE5ugUjO8NffQ39/2bF1Y7N2GmJWJrJt3Dlidl9EFHXC5dtLDgYo4LBEy3cYukpYnD5Qy7TjtL4OQoUkU53rVywYXrsqD7Wdm/Cg5A4EmNjns9jBPmSoMYREpwHprghkCR8TDxkFcyRtx0f5PYQzNw1e7vAe8GvwwQ9lgDoV4+fn9Tnty2kpnGPbQiDjRifP7UkHGVA5mb1QAI9chXNkfzC39jmsS6K6jTKxRt+nVe9DKuUxlhW1+qgALyHatZRU5dnuO8MpreCXFw7EFF3d1F8bIEcilg4D5U7mXjCY63rkBK2qfwk/FUlbHeWdoH9YkjOD2gumNvz9bpdfDVEc/uMyZwFpXE9mmey/8g4NUGO5pugTIPv46+iFSyrbwxJ2mVcE8GUyP2S9l3YGPdi3wrCFG1O/HNhmEzVMd+HgiyknER+8//jcP8Xk3q8nLhMhkTe5ZAjPlRpl0W4icDjzJWwU8h/dD0+zMsmIqVD/Du3QhQm2NRsLw8JT+qRatA5EA=
  app: cssconf-walle
  on:
    repo: necccc/cssconf-walle
env:
  global:
  - GH_REF: github.com/necccc/cssconf-walle.git
  - secure: sbTtbDKMpdeDJyPHH2dSfyV5IEZOtGO096Q+Tbd9nlzhvIA7WF/k+QrsaPnUCReJo6XdoISE3ftVDcDOUifNr9S3Ec8q2pnUy42iYgk4KCflqIKNXxZc1v8nhOUmJ/mtfVZ6kKE14KjHH80QA+4iHS7lq+Y37+bzdE6qATk/XLhYEx/NWQT8wP9hJhkr+7RkW3BzI6YkaUJyRbsbxFImvTz6uzl7LRerQDPsDzHIwGOEbBbkUtp15YJ/RZp9M4kyTJuQcxmeCC4zi75UOhS/JFoxPWbAH+Jvp5cV4coK9NK0IK/Cnu2HcroKk4UzxFErspj24Sk/eWtuugkOCbs1XrFv41mEF0xTWBke2w2XiW8mvvlIGWvJrRQb2vx7LNDo8te4z03HUiNGGmPOElOL/qmuYIr7UPP9AgFKDc6XyIrmhx1SNBH2O66faGT5hKjcnTnTWCBdYtB/U6Qb0dQpV1i1HwsOlc8s6HnmEcjnwFJ74RN6veyIJfeiiZSWusxNXSp3K+3nvUbAYcrqSHZ3fX02vv8jSTwVIi2XmvJGsxqDnSaI+GL/DrjCBwNkq9x5Rr5QY5N5gWUBaLiOVdQzxDjsVnA9BRCBJKTwykxZyfZrc6ly8ndpDp6Kcsn38GWwfhG7UFWN+JlJ1KsJ/RlsObQCDltQlx4uAhtyz5VOtRI=
